version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis_test
    ports:
      - "6379:6379"
    networks:
      - caching_network
    restart: always
    environment:
      - REDIS_PASSWORD=yourpassword

networks:
  caching_network:
    driver: bridge
