global:
  scrape_interval: 15s  # How often to scrape targets

scrape_configs:
  - job_name: 'metrics'
    static_configs:
      - targets: ['host.docker.internal:5268']
        
  - job_name: 'prometheus'
    static_configs:
      - targets: [ 'localhost:9090' ]
        
  - job_name: 'webapplication1'
    static_configs:
      - targets: ['host.docker.internal:5183']